[package]
name = "aoc-2020"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc_lib = { version = "0.1.0", path = "../aoc_lib" }
bitvec = "1.0.1"
itertools = "0.12.1"
lazy-regex = "3.3.0"
pathfinding = "4.11.0"
